# -*- coding: utf-8 -*-
"""Paule_S-CSPC315_Knapsack Problem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--V1LPriEMixXEaHwLHRTEHOfVP8nhaD

# Name: Faith Moselle O. Paule
# Program Code: BCS35
# S-CSPC315
# Due: November 30

0-1 Knapsack Problem Dynamic Programming Program
"""

print("Example Problem: \nval = [1,4,5,7] \nwt = [1,3,4,5] \nmax W = 7\n")
def knapsack(W, wt, val, n):
    K = [[0] * (W+1) for i in range (n+1)]
    #print(K)
    for i in range(n+1):
        for w in range(W+1):
            if(i == 0 or w == 0):
                K[i][w] = 0
            elif(wt[i-1] <= w):
                K[i][w] = max(val[i-1] + K[i-1][w-wt[i-1]], K[i-1][w])
            else:
                K[i][w] = K[i-1][w]
    for i in K:
        for c in i:
            print(c,end = " ")
        print()
    return K[n][w]

val = [1,4,5,7]
wt = [1,3,4,5]
W = 7
n = len(val)
profit = knapsack(W, wt, val, n)
print("Maximum Profit achieved with this knapsack: ")
print(profit)

# code from tutorialspoint, revised by Prof.T.R.Herradura

#Knapsack Problem #1
print("\nProblem #1 Using the provided code, run the following inputs.\nW = { 3, 4, 5, 6 } \nV = { 20, 8, 10, 25 } \nmax W = 8\n")
def knapsack(W, wt, val, n):
    K = [[0] * (W+1) for i in range (n+1)]
    #print(K)
    for i in range(n+1):
        for w in range(W+1):
            if(i == 0 or w == 0):
                K[i][w] = 0
            elif(wt[i-1] <= w):
                K[i][w] = max(val[i-1] + K[i-1][w-wt[i-1]], K[i-1][w])
            else:
                K[i][w] = K[i-1][w]
    for i in K:
        for c in i:
            print(c,end = " ")
        print()
    return K[n][w]

val = [20,8,10,25]
wt = [3,4,5,6]
W = 8
n = len(val)
profit = knapsack(W, wt, val, n)
print("Maximum Profit achieved with this knapsack: ")
print(profit)

#Knapsack Problem #2
print("\n\nProblem #2 Using the provided code, run the following inputs.\nW = { 1, 2, 3, 5 }\nV = { 30, 70, 50, 60 }\nmax W = 5\n")

def knapsack(W, wt, val, n):
    K = [[0] * (W+1) for i in range (n+1)]
    #print(K)
    for i in range(n+1):
        for w in range(W+1):
            if(i == 0 or w == 0):
                K[i][w] = 0
            elif(wt[i-1] <= w):
                K[i][w] = max(val[i-1] + K[i-1][w-wt[i-1]], K[i-1][w])
            else:
                K[i][w] = K[i-1][w]
    for i in K:
        for c in i:
            print(c,end = " ")
        print()
    return K[n][w]

val = [30,70,50,60]
wt = [1,2,3,5]
W = 5
n = len(val)
profit = knapsack(W, wt, val, n)
print("Maximum Profit achieved with this knapsack: ")
print(profit)

