# -*- coding: utf-8 -*-
"""Paule_CSIS312_102224

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10feizoPtnT_Uji_d6riw44q9IGOCNUfs

*   Name: Faith Moselle O. Paule
*   Program Code: BCS35
*   CSIS312
*   October 22, 2024

This Python script is part of an NLP pipeline demonstration for a class assignment.
The pipeline includes steps such as text cleaning, tokenization, stopword removal,
and stemming, using the NLTK library.
"""

# Import necessary libraries
import nltk
nltk.download()

# Import pandas for data manipulation and analysis
import pandas as pd

# Load the dataset (assumed to be in tab-separated values format) and print the first few rows
data = pd.read_csv('smsspamcollection.tsv', sep="\t", header=None)
data.head()
# Rename columns for better readability
data.columns = ['label', 'message', 'length', 'punct']
# Display the updated data with the new column names
data.head()

"""# Print basic information about the dataset, including the number of rows and columns"""

print(f'Input data has {len(data)} rows, {len(data.columns)} columns')

print(f'ham={len(data[data["label"]=="ham"])}')

print(f'spam={len(data[data["label"]=="spam"])}')

print(f"Number of nulls in label: {data['label'].isnull().sum()}")
print(f"Number of nulls in message: {data['message'].isnull().sum()}")

"""#Lecture Note
NLP Pipeline:
Raw Text->Tokenization->Text Cleaning->Vectorization->ML Algo.->Filter
"""

"I am teaching NLP" == "I am teaching NLP."

# Import the string library to handle punctuation removal
import string
string.punctuation
#The following are the punctuations identified, to be removed
#Output should be: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

# Function to remove punctuation from a given text
def remove_punct(text):
  text_nopunct = "".join([char for char in text if char not in string.punctuation])
  return text_nopunct

# Apply punctuation removal to the 'message' column
data['msg_clean'] = data['message'].apply(lambda x: remove_punct(x))
# Display the updated dataset with cleaned messages
data.head()

# Tokenization Split the cleaned text into tokens (words)
import re # regular expression
# Function to tokenize a given text based on non-word characters (punctuation, spaces, etc.)
def tokenize(text):
  tokens = re.split('\W+', text)
  return tokens

# Apply the tokenization function to the cleaned messages
data['msg_tokenized'] = data['msg_clean'].apply(lambda x: tokenize(x.lower()))
data.head()

# Download the stopwords corpus
nltk.download('stopwords')

# Now you can access the stopwords
stopwords = nltk.corpus.stopwords.words('english')

# Display the first 10 stopwords
print(stopwords[0:10])

# Function to remove stopwords
def remove_stopwords(txt_tokenized):
  text_clean = [word for word in txt_tokenized if word not in stopwords]
  return text_clean

# Apply the remove_stopwords function to the tokenized column
data['msg_nosw'] = data['msg_tokenized'].apply(lambda x: remove_stopwords(x))
data.head()

# Stemming: Reduce words to their root form (e.g., 'running' becomes 'run')
# Import the PorterStemmer from the NLTK library
from nltk.stem import PorterStemmer
ps = PorterStemmer()
dir(ps)

print(ps.stem('coder')) #Noun
print(ps.stem('coding')) #Verb
print(ps.stem('code')) #Noun

print(ps.stem('data')) #Singular
print(ps.stem('datum')) #Plural

print(ps.stem('bowl'))
print(ps.stem('bowling'))
print(ps.stem('bowler'))

# Function to apply stemming to a list of tokenized words
def stemming(tokenized_text):
  text = [ps.stem(word) for word in tokenized_text]
  return text

# Apply the stemming function to the tokenized and cleaned messages
data['msg_stemmed'] = data['msg_nosw'].apply(lambda x: stemming(x))
data.head()

# Stemming import summary:
# The PorterStemmer library is used to reduce words to their base or root form.
from nltk.stem import PorterStemmer
ps = PorterStemmer() #is called porter stemmer method