# -*- coding: utf-8 -*-
"""Paule_Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpezVKa4XVX7IWCp51Dr2AF4Tfta_1Fa
"""

# Programmed by: Faith Paule
# BCS35
# Due: Sep 19
# S-CSIS311LA
# Using Anaconda or Google Colab, solve the machine problem.
# Evaluate, analyze, and explain the steps using your chosen tool.
# Use the dataset housing. After completing the solution, create two copies: one in PDF format and one in Python (.py) format.
# Submit both files to the folder provided in MS Teams.
#Steps:
# 1. Import the libraries
# 2. Load the data
# 3. Setup the data
# 4. Prepare the data processing
# 5. Train the model
# 6. Test the model
# 7. Print the predictions
# 8. Visualize the model
# Objective: To predict the Median House Value based on Median Income

# Importing libraries required
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

SEED = 42
np.random.seed(SEED)

# 1. Load the dataset
df = pd.read_csv('housing.csv')
print(df.head())

# 2. Load the data frame.head()
print(df.head())

# 3. Load the df = df[['median_income', 'median_house_value']]
df = df[['median_income', 'median_house_value']]

# 4. Display dataframe information using df.info() and display df.head(10)
print(df.info())
print('')
print(df.head(10))

# I. Data Preparation

# 5. What values do you see?
print(df.describe())

"""# 5. What values do you see?
The Values I see are the summary statistics for the numerical columns in the data set: count, mean, standard deviation, min and max, quartiles. This statistics are the overall distibution and range of the data.
"""

# 6. What distributions do you see?
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.histplot(df['median_income'], kde=True)
plt.title('Distribution of Median Income')

"""# 6. What distributions do you see?
I see that most households have lower to mid-range incomes, and there are fewer households with very high incomes.
"""

# 7. What relationships do you see?
plt.figure(figsize=(8, 6))
sns.scatterplot(x='median_income', y='median_house_value', data=df)
plt.title('Relationship between Median Income and Median House Value')
plt.show()

"""# 7. What relationships do you see?
I see the relationship between median_income and median_house_value. It depicts that people with high income tend to have more expensive houses.

# 8. What relationships do you think might benefit the prediction problem?
To improve predictions in this problem, understanding the relationship between median income and median house value is crucial. The scatter plot from your exploratory analysis suggests there is a general correlation between median income and house value this is because when people earn more, houses tend to be more expensive. This is why a simple model works well for predicting house prices based on income.

# 9. What ideas about the domain does the data spark?
The relationship between median_income and median_house_value indicates that housing value is tightly linked to income levels. Higher-income areas tend to have more expensive houses, suggesting income inequality might be a driving factor in the housing market.
"""

# 10. Display all columns, head, tail and info using df.columns, df.head(), df.tail() and df.info()
print(df.columns)
print(df.head())
print(df.tail())
print(df.info())

# 11. Get an overall sense of the data shape using df.describe()
print(df.describe())

# This will show only features that have nonzero missing values.
df_na = df.isna().sum()
df_na

# Limit to categorical data using df.select_dtypes()
df_cat = df.select_dtypes(include=['object'])
df_cat.nunique()

# Limit to numerical data df.select_dtypes()
df_num = df.select_dtypes(include=['number'])
df_num.nunique()

#Look at correlations in the numerical independent variables as well as the dependent
# variables by executing df_num.corr()
df_num.corr()

# 12. Group the data and sort in ascending order
df.groupby(by='median_house_value').count().sort_values('median_house_value',
ascending=False).head(10)

# 13. Plot the data using scatterplot

# Scatter plot
df.plot.scatter('median_income', 'median_house_value')

# Boxplot
sns.boxplot(y='median_house_value', data=df)

# Violin plot
sns.violinplot(y='median_house_value', data=df)

# Joint plot with regression line
sns.jointplot(x="median_income", y="median_house_value", data=df, kind="reg")

# 14. Removing Outliears

df.drop(df[df['median_house_value']>500000].index, inplace=True)
_ = sns.violinplot(y='median_house_value', data=df)
_ = sns.jointplot(x="median_income", y="median_house_value", data=df, kind="reg")

# II. Preparing the data for training and testing
# 1) Divide our independent and dependent variable into two separate variables.
# 2) Split the data into training and testing datasets.

# 1)

x = df.iloc[:,0].values.reshape(-1,1) #input
y = df.iloc[:,1].values # output (dependent variable)

# 2) Splitting our data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=False, random_state=SEED)

# III. Train the Model
# Import the Linear Regression Algorithm
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
#Train the model
regressor.fit(x_train, y_train)

# 15. Visualize the trained model

#y=mx+c (Linear Regression Model)
line = regressor.coef_*x + regressor.intercept_

#Lets plot this on the scatter plot
plt.scatter(x, y)
plt.plot(x, line, 'r');
plt.xlabel('Median House Value')
plt.ylabel('Median Income')
plt.title('Median House Value vs Median Income')
plt.show()