# -*- coding: utf-8 -*-
"""Paule_CSPC315_MergeSort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJa59IsBwlf0gGtwxdVUIVJyW6rcQsAy
"""

# Name: Faith Moselle O. Paule
# BCS35
# CSPC315
'''Create a  mergesort program - divide and conquer design technique using any of your preferred programming language. NOTE : refer to Module for the sample algortihm
Run the program using this array with n=8 elements as input.
Trace the program by printing or output the following elements in this order:
Upload your program and the screenshot of your code and output of your program when run.'''

def merge_sort_with_trace(arr, depth=0): #Function
    # Setup the indentation based on the recursion depth to format the tracing output.
    indent = "  " * depth
    print(f"{indent}Splitting: {arr}")

    # Base case: If the array has one or no elements, it is already sorted.
    if len(arr) > 1:
        # Split the array into two halves.
        mid = len(arr) // 2
        left_half = arr[:mid]  # Left half of the array.
        right_half = arr[mid:]  # Right half of the array.

        # Recursively sort the left half.
        merge_sort_with_trace(left_half, depth + 1)
        # Recursively sort the right half.
        merge_sort_with_trace(right_half, depth + 1)

        # Initialize pointers for left_half (i), right_half (j), and original array (k).
        i = j = k = 0

        # Merge the left and right halves into the original array.
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                # Add the smaller element from the left half to the array.
                arr[k] = left_half[i]
                i += 1
            else:
                # Add the smaller element from the right half to the array.
                arr[k] = right_half[j]
                j += 1
            k += 1

        # Add any remaining elements from the left half.
        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        # Add any remaining elements from the right half.
        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

        # Log the merged result for this level.
        print(f"{indent}Merging: {arr}")
    else:
        # When the base case is reached (one or no elements), log the array.
        print(f"{indent}Base case reached: {arr}")

# Input array to be sorted.
arr = [8, 3, 2, 9, 7, 1, 5, 4]
print("Original array:", arr)

# Call the merge sort function with tracing enabled.
merge_sort_with_trace(arr)

# Output the sorted array.
print("Sorted array:", arr)