# -*- coding: utf-8 -*-
"""Paule_ICTS311Lec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Qyp2JEdvS_o5_AND9TRu0xFIf3cJAP8

# Regression
"""

# Commented out IPython magic to ensure Python compatibility.
# Programmed by: Faith Paule
# BCS35
# Due: Sept 23
# Class Participation
# S-CSIS311LA

# %matplotlib inline
# Initial Imports
import numpy as np
from pylab import *

# Generate Random Data
pageSpeeds = np.random.normal(3.0, 1.0, 1000)
purchaseAmount = 100 - (pageSpeeds + np.random.normal (0, 0.1, 1000))*2

# Visualizes the relationship between pageSpeeds and purchaseAmount using a scatter plot.
scatter(pageSpeeds, purchaseAmount)

# scipy.stats.linregress to perform linear regression and obtain the slope, intercept, R-squared value, p-value, and standard error for the relationship.
from scipy import stats
# Linear Regression
slope, intercept, r_value, p_value, std_err = stats.linregress(pageSpeeds, purchaseAmount)

# R-Squared Value: Measures how well the regression line fits the data.
# Higher values indicate a better fit.
r_value ** 2

import matplotlib.pyplot as plt

def predict(x):
  return slope * x + intercept

# function predict(x) to calculate the predicted values based on the
# linear regression and plots the regression line over the scatter plot
fitline = predict(pageSpeeds)

#Plotting Fit Line
# After generating the regression line (fitline), it is plotted alongside the data points.
plt.scatter(pageSpeeds, purchaseAmount)
plt.plot(pageSpeeds, fitline, c='r')

"""# Your Turn
Try increasing the random variation in the test data, and see what effect it has on the r-squared error value. Explain you observation and interpretation
"""

# Increasing Variation
# Increase the random variation in the test data, and see what effect it has on the r-squared error value.
# Explain you observation and interpretation
pageSpeeds = np.random.normal(3.0, 2.0, 2000)
purchaseAmount = 100 - (pageSpeeds + np.random.normal(0, 2.0, 2000)*2)

from scipy import stats
slope, intercept, r_value, p_value, std_err = stats.linregress(pageSpeeds, purchaseAmount)

def predict(x):
  return slope * x + intercept

fitline = predict(pageSpeeds)

plt.scatter(pageSpeeds, purchaseAmount)
plt.plot(pageSpeeds, fitline, c='r')

# Linear Regression
r_value ** 2

"""# Your Turn: Explanation
The random variation (noise) in purchaseAmount was increased from np.random.normal(0, 0.1, 1000) to np.random.normal(3.0, 2.0, 2000) to see how a higher level of randomness affects the R-squared value.

The r_value ** 2 will show the R-squared value, which is expected to decrease as the random variation increases, indicating a weaker fit of the model to the data.

# Polynomial Regression
"""

# Commented out IPython magic to ensure Python compatibility.
# What if your data doesn't look linear at all? let's look at some more realistic-looking page speed / purchase data:

# %matplotlib inline
import numpy as np
from pylab import *

np.random.seed(2)
pageSpeeds = np.random.normal(3.0, 1.0, 1000)
purchaseAmount = np.random.normal(50.0, 10.0, 1000) / pageSpeeds
scatter(pageSpeeds, purchaseAmount)

x = np.array(pageSpeeds)
y = np.array(purchaseAmount)

# Polynomial Fit
p4 = np.poly1d(np.polyfit(x, y, 4)) # Fits a 4th-degree polynomial to the data
print(p4)

import matplotlib.pyplot as plt

xp = np.linspace(0,7,100)
# Polynomial Curve
plt.scatter(x,y)
plt.plot(xp ,p4(xp),c='r')
plt.show()

# R-Squared for Polynomial Fit
from sklearn.metrics import r2_score
r2 = r2_score(y, p4(x))
print(r2)

"""# Your Turn
Try different polynomial orders. Can you get a better fit with higher orders?. Do you start to see overfitting, even though the r-squared score looks good for this particula dataset. Try p4 = np.poly1d(np.polyfit(x,y,1)) and np.poly1d(np.polyfit(x,y,8)) and third degree np.poly1d(np.polyfit(x,y,8)). Explain if theres overfitting explain your interpretation and observation.
"""

# Polynomial fits and Overfitting Evaluation

# Fit a 1st-degree polynomial (Linear)
p1 = np.poly1d(np.polyfit(x, y, 1))
r2_p1 = r2_score(y, p1(x))
print(f"1st-degree polynomial (Linear) R-squared: {r2_p1}")

# Plot 1st-degree polynomial
plt.scatter(x, y)
plt.plot(xp, p1(xp), c='r', label="1st Degree Fit (Linear)")
plt.legend()
plt.show()

# Fit a 3rd-degree polynomial
p3 = np.poly1d(np.polyfit(x, y, 3))
r2_p3 = r2_score(y, p3(x))
print(f"3rd-degree polynomial R-squared: {r2_p3}")

# Plot 3rd-degree polynomial
plt.scatter(x, y)
plt.plot(xp, p3(xp), c='g', label="3rd Degree Fit")
plt.legend()
plt.show()

# Fit an 8th-degree polynomial
p8 = np.poly1d(np.polyfit(x, y, 8))
r2_p8 = r2_score(y, p8(x))
print(f"8th-degree polynomial R-squared: {r2_p8}")

# Plot 8th-degree polynomial
plt.scatter(x, y)
plt.plot(xp, p8(xp), c='b', label="8th Degree Fit")
plt.legend()
plt.show()

# Display R-squared for all fits
print(f"1st-degree polynomial R-squared: {r2_p1}")
print(f"3rd-degree polynomial R-squared: {r2_p3}")
print(f"8th-degree polynomial R-squared: {r2_p8}")

"""# Your Turn: Explanation
- 1st-degree polynomial (Linear): A linear fit is applied first, which may provide a lower R-squared if the data isn't perfectly linear.
- 3rd-degree polynomial: A 3rd-degree fit may capture more complex patterns in the data without excessive overfitting.
- 8th-degree polynomial: An 8th-degree fit will likely fit the data very well (high R-squared), but may overfit, capturing noise rather than true patterns in the data.

Overfitting happens when a model learns the random noise in the data instead of the real pattern. This can look like a model that fits the data too closely, even in ways that don't make sense. For example, a model that's too complex might fit the data perfectly, but it could be overreacting to small, unimportant details.

# Multiple Regression
"""

import pandas as pd
# Loading Data
df = pd.read_excel('cars.xls')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np

# Group by Mileage using pd.cut() and the average price which is computed for each group
df1 = df[['Mileage', 'Price']]
bins = np.arange(0,50000,10000)
groups = df1.groupby(pd.cut(df1['Mileage'], bins)).mean()
print(groups.head())
# Plots the mean price for each mileage group
groups['Price'].plot.line()

import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

X = df[['Mileage', 'Cylinder', 'Liter', 'Doors']]
y = df['Price']

X[['Mileage', 'Cylinder', 'Liter', 'Doors']] = scale.fit_transform(X[['Mileage', 'Cylinder', 'Liter', 'Doors']].values)

print(X)

est = sm.OLS(y, X).fit()

est.summary()

y.groupby(df.Doors).mean()

scaled = scale.transform([[45000, 8, 4, 4]])
print(scaled)
predicted = est.predict(scaled[0])
print(predicted)

"""# Your Turn
Mess around with the sample input data, and see if you can create a measurable influence of number of doors on price. Have some fun with it- Why stop at 4 doors? say, cars that have 5,7,8 door 10 if possible
"""

# Messing Around with Door Counts

# Create a synthetic dataset with varied number of doors
np.random.seed(42)  # For reproducibility
n_samples = 1000

# Randomly generate data for mileage, cylinder, liter, and number of doors
mileage = np.random.randint(10000, 100000, n_samples)
cylinder = np.random.choice([4, 6, 8], n_samples)
liter = np.random.uniform(1.0, 5.0, n_samples)
# Allowing for 2 to 10 doors
doors = np.random.choice([2, 3, 4, 5, 6, 7, 8, 9, 10], n_samples)

# Generate prices influenced by mileage, cylinder, liter, and number of doors
price = 20000 - (mileage * 0.1) + (cylinder * 1000) + (liter * 3000) + (doors * 1500) + np.random.normal(0, 2000, n_samples)

# Create a DataFrame
car_data = pd.DataFrame({
    'Mileage': mileage,
    'Price': price,
    'Cylinder': cylinder,
    'Liter': liter,
    'Doors': doors
})

# Perform Multiple Regression
X = car_data[['Mileage', 'Cylinder', 'Liter', 'Doors']]
y = car_data['Price']

# Standardize the features
X[['Mileage', 'Cylinder', 'Liter', 'Doors']] = scale.fit_transform(X[['Mileage', 'Cylinder', 'Liter', 'Doors']])

# Fit the model
est = sm.OLS(y, X).fit()

# Display the regression summary
print(est.summary())

# Analyzing the influence of doors on price
door_effect = y.groupby(car_data.Doors).mean()
print(door_effect)

# Visualizing the effect of the number of doors on average price
door_effect.plot(kind='bar', title='Average Price by Number of Doors')
plt.ylabel('Average Price')
plt.xlabel('Number of Doors')
plt.show()

"""# K_Fold_CROSS_Validation"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
from pylab import *

np.random.seed(2)
pageSpeeds = np.random.normal(3.0, 1.0, 100)
purchaseAmount = np.random.normal(50.0, 30.0, 100) / pageSpeeds

scatter(pageSpeeds, purchaseAmount)

trainX = pageSpeeds[:80]
testX = pageSpeeds[80:]

trainY = purchaseAmount[:80]
testY = purchaseAmount[80:]

scatter(trainX, trainY)

scatter(testX, testY)

x = np.array(trainX)
y = np.array(trainY)

p4 = np.poly1d(np.polyfit(x, y, 8))

import matplotlib.pyplot as plt

xp = np.linspace(0,7,100)
axes = plt.axes()
axes.set_xlim([0,7])
axes.set_ylim([0,200])
plt.scatter(x,y)
plt.plot(xp, p4(xp), c='r')
plt.show()

testx = np.array(testX)
testy = np.array(testY)

axes = plt.axes()
axes.set_xlim([0,7])
axes.set_ylim([0,200])
plt.scatter(x,y)
plt.plot(xp, p4(xp), c='r')
plt.show()

from sklearn.metrics import r2_score
r2 = r2_score(testy, p4(testx))
print(r2)

from sklearn.metrics import r2_score

r2 = r2_score(np.array(trainY), p4(np.array(trainX)))

print(r2)

"""# Your Turn
Try measuring the error on the test data using different degree polynomial fits. What degree works best?
"""

# %matplotlib inline
import numpy as np
from pylab import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

np.random.seed(2)

pageSpeeds = np.random.normal(3.0, 1.0, 100)
purchaseAmount = np.random.normal(50.0, 30.0, 100) / pageSpeeds

# Scatter plot of original data
scatter(pageSpeeds, purchaseAmount)
xlabel("Page Speed")
ylabel("Purchase Amount")
title("Original Data")
show()

# Split data into training and test sets
trainX = pageSpeeds[:80]
testX = pageSpeeds[80:]

trainY = purchaseAmount[:80]
testY = purchaseAmount[80:]

# Function to evaluate polynomial fit with different degrees
def evaluate_polynomial_fit(X_train, y_train, X_test, y_test, max_degree=8):
  """
  Evaluates polynomial fits for different degrees and returns the best degree
  based on mean squared error (MSE) on the test data.

  Args:
      X_train (numpy.ndarray): Training data features.
      y_train (numpy.ndarray): Training data target values.
      X_test (numpy.ndarray): Test data features.
      y_test (numpy.ndarray): Test data target values.
      max_degree (int, optional): Maximum degree of polynomial to evaluate.
          Defaults to 8.

  Returns:
      int: The degree of the polynomial with the lowest MSE on the test data.
  """
  best_degree = 1  # Initialize with linear regression
  best_mse = float('inf')

  for degree in range(1, max_degree + 1):
    # Create polynomial features
    poly = PolynomialFeatures(degree=degree, include_bias=False)
    X_train_poly = poly.fit_transform(X_train.reshape(-1, 1))
    X_test_poly = poly.transform(X_test.reshape(-1, 1))

    # Fit a linear regression model
    model = LinearRegression()
    model.fit(X_train_poly, y_train)


    # Make predictions on the test data
    y_pred = model.predict(X_test_poly)

    # Calculate mean squared error (MSE)
    mse = mean_squared_error(y_test, y_pred)


    # Update best degree if lower MSE is found
    if mse < best_mse:
      best_degree = degree
      best_mse = mse

  return best_degree

# Find the best degree of polynomial fit
best_degree = evaluate_polynomial_fit(trainX, trainY, testX, testY)
print(f"Best degree based on  mean squared error (MSE): {best_degree}")

# Fit a polynomial model of the best degree
poly = PolynomialFeatures(degree=best_degree, include_bias=False)
X_train_poly = poly.fit_transform(trainX.reshape(-1, 1))
X_test_poly = poly.transform(testX.reshape(-1, 1))

model = LinearRegression()
model.fit(X_train_poly, trainY)

# Make predictions on the test data
y_pred = model.predict(X_test_poly)

# Plot the data and best fit curve
xp = np.linspace(0, 7, 100)
axes = plt.axes()
axes.set_xlim([0, 7])
axes.set_ylim([0, 200])
plt.scatter(trainX, trainY, label="Training Data")
plt.scatter(testX, testY, label="Test Data")
plt.plot(xp, model.predict(poly.transform(xp.reshape(-1, 1))), c='r', label=f"Polynomial Fit (Degree: {best_degree})")
plt.xlabel("Page Speed")
plt.ylabel("Purchase Amount")
plt.title("Polynomial Fit with Error Measurement")
plt.legend()
show()